Add policy for provisioning cisagov/cyhy-tf-root
cisagov/cool-accounts-cyhy-tf-root pull request #3
Opened 2024-09-27 19:43 UTC by dav3r

#  #

## 🗣 Description ##

This PR adds a policy that allows the provisioning of the resources in [cisagov/cyhy-tf-root](https://github.com/cisagov/cyhy-tf-root).

## 💭 Motivation and context ##

Without this policy, we won't be able to apply the Terraform in [cisagov/cyhy-tf-root](https://github.com/cisagov/cyhy-tf-root).

## 🧪 Testing ##

After I created this policy, I verified that I was able to successfully `terraform apply` and `terraform destroy` all of the resources for https://github.com/cisagov/cyhy-tf-root/pull/12.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

2024-10-11 15:25 UTC, dv4harr10 approved these changes

2024-10-11 17:36 UTC, jsf9k requested changes
Don't you need to update the `terraform-docs` output in `README.md` as well?

2024-10-11 17:45 UTC, dav3r commented
> Don't you need to update the `terraform-docs` output in `README.md` as well?

Thanks for the reminder!  Please see https://github.com/cisagov/cool-accounts-cyhy-tf-root/pull/3/commits/daa55fbb40c31e879e2decb658479db569fb328f.

2024-10-11 17:59 UTC, jsf9k approved these changes

2024-10-16 18:51 UTC, dav3r commented
@mcdonnnj - Note https://github.com/cisagov/cool-accounts-cyhy-tf-root/pull/3/commits/0f9c2cfd77e0d72675f8b61894154d0e6fabd9c4 per our discussion yesterday.

2024-10-16 19:55 UTC, jsf9k approved these changes

2024-10-25 18:28 UTC, jsf9k approved these changes
Approved even harder!

2024-11-21 16:29 UTC, jsf9k requested changes

2024-11-21 16:29 UTC, jsf9k commented on variables.tf
> +  description = "The description to associate with the IAM policy that allows sufficient permissions to provision all AWS resources required by cisagov/cyhy-tf-root."
```suggestion
  description = "The description to associate with the IAM policy that allows sufficient permissions to provision all AWS resources required by cisagov/cyhy-tf-root."
  nullable    = false
```

2024-11-21 16:29 UTC, jsf9k commented on variables.tf
> +  description = "The name to assign the IAM policy that allows sufficient permissions to provision all AWS resources required by cisagov/cyhy-tf-root."
```suggestion
  description = "The name to assign the IAM policy that allows sufficient permissions to provision all AWS resources required by cisagov/cyhy-tf-root."
  nullable    = false
```

2024-11-21 16:42 UTC, jsf9k approved these changes

2024-11-21 18:56 UTC, felddy approved these changes
💎Approving harder still! 💎 
![pingu-smack](https://github.com/user-attachments/assets/08b7ad34-fb5c-4640-ba66-d2a7a7f1744f)

2024-11-21 19:17 UTC, jsf9k commented
> 💎Approving harder still! 💎 
> ![pingu-smack](https://github.com/user-attachments/assets/08b7ad34-fb5c-4640-ba66-d2a7a7f1744f)
> 

Pingu!

2024-11-22 15:20 UTC, merged